# The docker-compose.yml file describes the services that make your app. 
# In this those services are Postgres DB + cloudbeaver

version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: postgresql
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "world"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d/
      - .:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: /usr/bin/pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER}
      interval: 5s
      timeout: 10s
      start_period: 10s
  

  db_client:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    depends_on:
      - database
    restart: always
    hostname: localhost
    ports:
      - '8080:8978'
